const europeanAllFootballTeams = [
  "Albania",
  "Andorra",
  "Armenia",
  "Austria",
  "Azerbaijan",
  "Belarus",
  "Belgium",
  "Bosnia Herzegovina",
  "Bulgaria",
  "Croatia",
  "Cyprus",
  "Czech Republic",
  "Denmark",
  "England",
  "Estonia",
  "Faroe Islands",
  "Finland",
  "France",
  "Georgia",
  "Germany",
  "Gibraltar",
  "Greece",
  "Hungary",
  "Iceland",
  "Ireland",
  "Israel",
  "Italy",
  "Kazakhstan",
  "Kosovo",
  "Latvia",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Malta",
  "Moldova",
  "Montenegro",
  "Netherlands",
  "North Macedonia",
  "Northern Ireland",
  "Norway",
  "Poland",
  "Portugal",
  "Romania",
  "Russia",
  "San Marino",
  "Scotland",
  "Serbia",
  "Slovakia",
  "Slovenia",
  "Spain",
  "Sweden",
  "Switzerland",
  "Turkey",
  "Ukraine",
  "Wales",
];

const simulatedTeams = [
  "equipo 1",
  "equipo 2",
  "equipo 3",
  "equipo 4",
  "equipo 5",
  "equipo 6",
  "equipo 7",
  "equipo 8",
  "equipo 9",
  "equipo 10",
  "equipo 11",
  "equipo 12",
  "equipo 13",
  "equipo 14",
  "equipo 15",
  "equipo 16",
  "equipo 17",
  "equipo 18",
  "equipo 19",
  "equipo 20",
  "equipo 21",
  "equipo 22",
  "equipo 23",
  "equipo 24",
];

export { europeanAllFootballTeams, simulatedTeams };
